/**
 * WebSocket Message Schema - Re-exports from Unified Frontend Schema
 *
 * This file re-exports the unified WebSocket message types from the frontend.
 * The frontend unified schema (/frontend/src/types/ws_messages.ts) is the SINGLE SOURCE OF TRUTH.
 *
 * IMPORTANT: Do NOT edit this file. All changes should be made to:
 * /frontend/src/types/ws_messages.ts
 *
 * This file exists for backward compatibility and to provide a single import point.
 */

// Re-export everything from the unified frontend schema

export * from '../frontend/src/types/ws_messages';

// For backward compatibility, preserve the old interface names if needed
// The exports above already include all types from the unified schema

